# Generated by Django 4.1.3 on 2022-11-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_alter_categories_title_alter_flowers_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='flowers',
            options={'ordering': ['title', 'price'], 'verbose_name': 'Цветы', 'verbose_name_plural': 'Цветы'},
        ),
    ]
