# Generated by Django 4.1.3 on 2022-11-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_alter_categories_options_alter_flowers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='num_of_purchases',
            field=models.IntegerField(default=0, verbose_name='Количество покупок'),
        ),
    ]
