# Generated by Django 4.1.3 on 2022-11-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_flowers_num_of_purchases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowers',
            old_name='num_of_purchases',
            new_name='number_of_purchases',
        ),
    ]
