# Generated by Django 4.1.3 on 2022-11-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_rename_num_of_purchases_flowers_number_of_purchases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowers',
            options={'ordering': ['title', 'price', 'number_of_purchases'], 'verbose_name': 'Цветы', 'verbose_name_plural': 'Цветы'},
        ),
    ]
